[package]
name = "lightblue_macro"
version = "0.1.0"
edition = "2021"

[lib]
name = "lightblue_macro"
proc-macro = true

[features]
default = []

[dependencies]
syn = { version = "2.0", features = ["full", "parsing", "printing"]}
quote = "1.0"
proc-macro2 = "1.0"
Inflector = "0.11"
